services:
  - type: web
    name: painel-emendas
    runtime: docker
    plan: standard
    healthCheckPath: /
    envVars:
      - key: MAX_UPLOAD_MB
        value: "900"
      - key: SECRET_KEY
        generateValue: true
